In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [12]:
dframe1

X         Y         Z
0  0.302900  1.081502 -2.044888
1  0.306062 -0.386353  2.027770
2  0.716037  0.468084 -0.400696
3  0.374599 -0.065562 -0.563253

In [13]:
dframe2

Y         Q         X
0 -1.204359 -0.587825  1.639740
1  0.255613 -1.313342  0.153718
2 -0.601171 -0.862312 -0.698521

In [14]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0  0.302900  1.081502 -2.044888       NaN
1  0.306062 -0.386353  2.027770       NaN
2  0.716037  0.468084 -0.400696       NaN
3  0.374599 -0.065562 -0.563253       NaN
0  1.639740 -1.204359       NaN -0.587825
1  0.153718  0.255613       NaN -1.313342
2 -0.698521 -0.601171       NaN -0.862312

In [15]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0  0.302900  1.081502 -2.044888       NaN
1  0.306062 -0.386353  2.027770       NaN
2  0.716037  0.468084 -0.400696       NaN
3  0.374599 -0.065562 -0.563253       NaN
4  1.639740 -1.204359       NaN -0.587825
5  0.153718  0.255613       NaN -1.313342
6 -0.698521 -0.601171       NaN -0.862312