In [1]:
import numpy as np

In [2]:
tensor = np.array([[[0,1,2],[1,2,3],[2,3,4]],
                   [[1,2,3],[2,3,4],[3,4,5]],
                   [[2,3,4],[3,4,5],[4,5,6]]])
print(tensor)

[[[0 1 2]
  [1 2 3]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[2 3 4]
  [3 4 5]
  [4 5 6]]]


In [3]:
print("\nElement at index (1,1,1):", tensor[1,1,1])


Element at index (1,1,1): 3


In [4]:
print("\nSlice along the first dimension:")
print(tensor[1,:,:])


Slice along the first dimension:
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [5]:
reshaped_tensor = np.reshape(tensor,(9,3))
print("\nReshaped tensor:")
print(reshaped_tensor)


Reshaped tensor:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [6]:
transposed_tensor = np.transpose(tensor, axes=[2,1,0])
print("\nTranspodsed tensor:")
print(transposed_tensor)


Transpodsed tensor:
[[[0 1 2]
  [1 2 3]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[2 3 4]
  [3 4 5]
  [4 5 6]]]
