In [1]:
import numpy as np
from scipy.linalg import lu

In [2]:
matrix = np.array([[2,-1],[1,2]])
P,L,U = lu(matrix)

In [3]:
Q,R = np.linalg.qr(matrix)

In [4]:
cholesky = np.linalg.cholesky(matrix)

In [5]:
U_svd, S_svd, Vt_svd = np.linalg.svd(matrix)

In [6]:
print("\nLU Decomposition")
print("Permutation Matrix")
print(P)
print("Lower Triangular Matrix")
print(L)
print("Upper Triangular Matrix")
print(U)


LU Decomposition
Permutation Matrix
[[1. 0.]
 [0. 1.]]
Lower Triangular Matrix
[[1.  0. ]
 [0.5 1. ]]
Upper Triangular Matrix
[[ 2.  -1. ]
 [ 0.   2.5]]


In [7]:
print("\nQR Decomposition")
print("Orthogonal matrix Q")
print(Q)
print("Upper Triangular Matrix R")
print(R)



QR Decomposition
Orthogonal matrix Q
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
Upper Triangular Matrix R
[[-2.23606798e+00 -6.18106769e-17]
 [ 0.00000000e+00  2.23606798e+00]]


In [8]:
print("\nCholesky Decomposition")
print(cholesky)


Cholesky Decomposition
[[1.41421356 0.        ]
 [0.70710678 1.22474487]]


In [9]:
print("\nSingular Value Decomposition")
print("Left Singular Vector")
print(U_svd)
print("Singular Value, diagonal matrix")
print(S_svd)
print("Right Singular Vector")
print(Vt_svd)


Singular Value Decomposition
Left Singular Vector
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
Singular Value, diagonal matrix
[2.23606798 2.23606798]
Right Singular Vector
[[-1. -0.]
 [ 0.  1.]]
