In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1,1],[3,6]])
inverse = np.linalg.inv(matrix_a)
print("Result:")
print(inverse)

Result:
[[ 2.         -0.33333333]
 [-1.          0.33333333]]


In [3]:
matrix_b = np.array([[1,8,2],[3,7,5],[1,2,9]])
transpose = np.transpose(matrix_b)
print("Result:")
print(transpose)

Result:
[[1 3 1]
 [8 7 2]
 [2 5 9]]
