In [1]:
import numpy as np

In [2]:
matrix_A = np.array([[2,8],[3,10]])
matrix_B = np.array([[8,9],[1,7]])

In [3]:
Addition = matrix_A + matrix_B
print("Result:")
print(Addition)

Result:
[[10 17]
 [ 4 17]]


In [4]:
matrix_C = np.array([[9,2,19],[15,1,5],[8,0,17]])
matrix_D = np.array([[2,4,5],[6,8,11],[1,3,7]])

In [5]:
Subtraction = matrix_C - matrix_D
print("Result:")
print(Subtraction)

Result:
[[ 7 -2 14]
 [ 9 -7 -6]
 [ 7 -3 10]]
