In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([[3,5],[2,1]])
matrix_2 = np.array([[2,1],[1,5]])
result_A = np.dot(matrix_1,matrix_2)
print("Result:")
print(result_A)

Result:
[[11 28]
 [ 5  7]]


In [3]:
matrix_3 = np.array([[2,0,3],[5,1,0]])
matrix_4 = np.array([[1,0],[2,0],[1,5]])
result_B = np.dot(matrix_3,matrix_4)
print("Result:")
print(result_B)

Result:
[[ 5 15]
 [ 7  0]]


In [4]:
matrix_5 = np.array([[1,3,1],[2,2,3],[5,7,2]])
matrix_6 = np.array([[0,5,1],[2,3,1],[7,2,5]])
result_C = np.dot(matrix_5,matrix_6)
print("Result:")
print(result_C)

Result:
[[13 16  9]
 [25 22 19]
 [28 50 22]]
