In [1]:
import numpy as np
import pandas as pd

In [ ]:
mydays = ['Sun', 'Mon', 'Tue']
myexp = [34, 44, 29]

a_mydays = np.array(mydays)
a_myexp = np.array(myexp)

pd.Series(data=a_myexp, index=a_mydays)

Sun    34
Mon    44
Tue    29
dtype: int64

In [3]:
myexp[0]

34

In [4]:
a_myexp[0]

np.int64(34)

In [6]:
s_myexp = pd.Series(data=a_myexp, index=a_mydays)
s_myexp

Sun    34
Mon    44
Tue    29
dtype: int64

In [11]:
s_myexp.loc['Mon']

np.int64(44)

In [10]:
s_myexp.iloc[0]

np.int64(34)

In [12]:
my_nums = np.arange(1,10).reshape(3,3)
my_nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
pd.DataFrame(my_nums)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
my_index = ['Row1', 'Row2', 'Row3']
my_col = ['Col1','Col2', 'Col3']
df = pd.DataFrame(data=my_nums, index=my_index, columns=my_col)
df

Col1  Col2  Col3
Row1     1     2     3
Row2     4     5     6
Row3     7     8     9

In [15]:
pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]}, index=['first', 'second', 'third'])

A  B
first   1  4
second  2  5
third   3  6

In [17]:
df = pd.read_csv('Datasets/Piece_Dim.csv')
df.head()

Item_No  Length  Width  Height Operator
0  Item-1  102.67  49.53   19.69     Op-1
1  Item-2  102.50  51.42   19.63     Op-1
2  Item-3   95.37  52.25   21.51     Op-1
3  Item-4   94.77  49.24   18.60     Op-1
4  Item-5  104.26  47.90   19.46     Op-1

In [18]:
df = pd.read_csv('Datasets/Piece_Dim.csv', index_col='Item_No')
df.head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, Item-1 to Item-50
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Length    50 non-null     float64
 1   Width     50 non-null     float64
 2   Height    50 non-null     float64
 3   Operator  50 non-null     object 
dtypes: float64(3), object(1)
memory usage: 4.0+ KB


In [20]:
df.describe()

Length      Width     Height
count   50.000000  50.000000  50.000000
mean   100.128800  49.461400  20.014000
std      5.075593   2.615639   1.074069
min     89.820000  44.460000  17.370000
25%     95.675000  48.105000  19.375000
50%     99.830000  49.315000  19.930000
75%    104.402500  50.780000  20.595000
max    110.540000  55.760000  23.110000

In [23]:
df['Length'].head()

Item_No
Item-1    102.67
Item-2    102.50
Item-3     95.37
Item-4     94.77
Item-5    104.26
Name: Length, dtype: float64

In [24]:
df[['Length', 'Width']].head()

Length  Width
Item_No               
Item-1   102.67  49.53
Item-2   102.50  51.42
Item-3    95.37  52.25
Item-4    94.77  49.24
Item-5   104.26  47.90

In [25]:
df['Volume'] = df['Length'] * df['Width'] * df['Height']
df.head()

Length  Width  Height Operator         Volume
Item_No                                               
Item-1   102.67  49.53   19.69     Op-1  100128.476019
Item-2   102.50  51.42   19.63     Op-1  103460.896500
Item-3    95.37  52.25   21.51     Op-1  107186.104575
Item-4    94.77  49.24   18.60     Op-1   86796.431280
Item-5   104.26  47.90   19.46     Op-1   97184.290840

In [26]:
df['Volume'] = np.round(df['Length'] * df['Width'] * df['Height'], 2)
df.head()

Length  Width  Height Operator     Volume
Item_No                                           
Item-1   102.67  49.53   19.69     Op-1  100128.48
Item-2   102.50  51.42   19.63     Op-1  103460.90
Item-3    95.37  52.25   21.51     Op-1  107186.10
Item-4    94.77  49.24   18.60     Op-1   86796.43
Item-5   104.26  47.90   19.46     Op-1   97184.29

In [30]:
df.drop('Volume', axis=1).head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [31]:
df = df.drop('Volume', axis=1)
df.head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [32]:
df['Volume'] = np.round(df['Length'] * df['Width'] * df['Height'], 2)
df.head()

Length  Width  Height Operator     Volume
Item_No                                           
Item-1   102.67  49.53   19.69     Op-1  100128.48
Item-2   102.50  51.42   19.63     Op-1  103460.90
Item-3    95.37  52.25   21.51     Op-1  107186.10
Item-4    94.77  49.24   18.60     Op-1   86796.43
Item-5   104.26  47.90   19.46     Op-1   97184.29

In [33]:
df.drop('Volume', axis=1,inplace=True)

In [34]:
df.head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [35]:
df.loc['Item-1']

Length      102.67
Width        49.53
Height       19.69
Operator      Op-1
Name: Item-1, dtype: object

In [36]:
df.loc[['Item-1']]

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1

In [37]:
df.loc[['Item-1','Item-5']]

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [38]:
df.loc[['Item-1','Item-5'],['Length', 'Width', 'Height']]

Length  Width  Height
Item_No                       
Item-1   102.67  49.53   19.69
Item-5   104.26  47.90   19.46

In [39]:
df.iloc[0]

Length      102.67
Width        49.53
Height       19.69
Operator      Op-1
Name: Item-1, dtype: object

In [40]:
df.iloc[[0]]

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1

In [41]:
df.iloc[[0, 4]]

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-5   104.26  47.90   19.46     Op-1

In [42]:
df.iloc[[0, 4],[0, 1, 2]]

Length  Width  Height
Item_No                       
Item-1   102.67  49.53   19.69
Item-5   104.26  47.90   19.46

In [43]:
df.iloc[0:4,0:3]

Length  Width  Height
Item_No                       
Item-1   102.67  49.53   19.69
Item-2   102.50  51.42   19.63
Item-3    95.37  52.25   21.51
Item-4    94.77  49.24   18.60

In [45]:
df5 = df.iloc[0:5,0:3]
df5.describe()

Length     Width     Height
count    5.000000   5.00000   5.000000
mean    99.914000  50.06800  19.778000
std      4.479936   1.75102   1.062812
min     94.770000  47.90000  18.600000
25%     95.370000  49.24000  19.460000
50%    102.500000  49.53000  19.630000
75%    102.670000  51.42000  19.690000
max    104.260000  52.25000  21.510000

In [46]:
tens = np.arange(0, 101, 10)
tens

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [47]:
tens >= 60

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [49]:
tens[tens >= 60]

array([ 60,  70,  80,  90, 100])

In [52]:
df1 = df[df['Operator'] == 'Op-1']
df1.describe()

Length      Width     Height
count   25.000000  25.000000  25.000000
mean    99.547200  49.301200  20.024800
std      5.147417   2.955796   0.823514
min     89.820000  44.460000  18.600000
25%     95.510000  47.900000  19.510000
50%     98.730000  49.240000  19.940000
75%    104.260000  50.810000  20.360000
max    108.450000  55.760000  22.310000

In [53]:
df[(df['Length']  > 105) & (df['Operator'] == 'Op-1')]

Length  Width  Height Operator
Item_No                                
Item-6   105.18  49.39   20.36     Op-1
Item-13  105.72  50.04   20.06     Op-1
Item-17  107.69  48.18   19.33     Op-1
Item-18  106.83  50.81   19.12     Op-1
Item-23  108.45  44.46   22.31     Op-1

In [ ]:
df[(df['Length']  >= 95) & (df['Length'] <= 105)].head()

Length  Width  Height Operator
Item_No                                
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-5   104.26  47.90   19.46     Op-1
Item-7    97.35  48.05   20.22     Op-1

In [59]:
df[(df['Length']  >= 110) | (df['Width'] <= 45)]

Length  Width  Height Operator
Item_No                                
Item-8    99.35  44.59   21.03     Op-1
Item-23  108.45  44.46   22.31     Op-1
Item-41  110.54  51.07   21.95     Op-2