In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.21598965, -0.29367495, -0.96073814, -0.40639414, -0.71049713,
       -0.52178479, -0.31101212, -0.78580437, -2.56848448, -1.16323274])

In [6]:
B =np.random.randn(10)
B

array([ 0.09745566,  0.15031159,  1.03227582, -0.88300382,  0.8656721 ,
        0.51660247,  0.16373765, -0.03818531, -1.76478284,  1.00856095])

In [7]:
np.add(A,B)

array([ 0.31344531, -0.14336335,  0.07153769, -1.28939796,  0.15517497,
       -0.00518232, -0.14727447, -0.82398968, -4.33326732, -0.15467179])

In [8]:
np.maximum(A,B)

array([ 0.21598965,  0.15031159,  1.03227582, -0.40639414,  0.8656721 ,
        0.51660247,  0.16373765, -0.03818531, -1.76478284,  1.00856095])